spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:employee
    username: Lester
    password: Lester0090
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
